projects:
  fisslist-api:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        dev: 'http://localhost:4000'
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
